# Generated by Django 5.0.1 on 2024-05-04 09:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationModule', '0002_f2acodes_alter_bannedtokens_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f2acodes',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
