# Generated by Django 5.0.1 on 2024-05-04 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationModule', '0003_alter_f2acodes_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='f2acodes',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
