# Generated by Django 5.0.1 on 2024-05-05 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationModule', '0004_alter_f2acodes_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('create_p', models.BooleanField(default=False)),
                ('read_p', models.BooleanField(default=False)),
                ('update_p', models.BooleanField(default=False)),
                ('delete_p', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserRoles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorizationModule.roles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
