# Generated by Django 5.0.1 on 2024-05-06 08:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationModule', '0006_methodslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='methodslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
