# Generated by Django 5.0.1 on 2024-05-06 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationModule', '0007_alter_methodslog_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MethodsLog',
        ),
    ]
