# Generated by Django 5.0.1 on 2024-05-06 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorizationModule', '0008_delete_methodslog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userroles',
            name='role',
        ),
        migrations.RemoveField(
            model_name='userroles',
            name='user',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='UserRoles',
        ),
    ]
